version: '3.7'

services:
  db:
    image: "postgres"
    container_name: 'ks-db'
    restart: 'no'
    ports:
      - '5432:5432'
    volumes:
      - ./db/data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: khaja_station_db
      PGDATA : /var/lib/postgresql/data/pgdata
  redis:
    image: 'bitnami/redis:latest'
    container_name: 'ks-redis'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'
    volumes:
      - ./db/redis:/bitnami/redis/data
